### ISSUE TITLE
[Question] Do you Have Any Plan to support the Linux and MacOS Version?

### ISSUE THREAD

**Issue by ditokp** [galloscript/TexGraph-Public#1]
Hello, I just found your app in itch and download it. But my machine is on Linux. My question is do you have any plan to support the Linux and MacOS version?

Thank you for reading this.

**Comment by galloscript** [comment]
Hello, yes, of course it is planned to release builds for MacOS and Linux, but there is no specific date for that. I hope I can do it this year.

**Comment by ditokp** [comment]
Thank you for answering my question and have a nice day

**Comment by azagaya** [comment]
@galloscript hey, do you have any build instructions or dependencies needed? i could help testing for the Linux build. I had problems with MAC and opengl in my own soft, and i think opengl is going to be droped for mac.

**Comment by galloscript** [comment]
@azagaya This repository only contains the sources for the nodes and viewport shaders, the Public folder of TexGraph. This project is not open source, at least not for now, but thanks for offering your help

**Comment by azagaya** [comment]
> @azagaya This repository only contains the sources for the nodes and viewport shaders, the Public folder of TexGraph. This project is not open source, at least not for now, but thanks for offering your help

Oh, ok. Anyways, it seems to work fine in Linux with wine. It's a really impressive soft. Great work!
