### ISSUE TITLE
disappearing window

### ISSUE THREAD

**Issue by AttilaART** [galloscript/TexGraph-Public#11]
The viewport has disappeared and I dont know how to get it back. (I have tried opening & closing the program or making a new graph)

Thanks in advance

![asd](https://user-images.githubusercontent.com/59292387/71528122-bd2e4b80-28de-11ea-85a1-2020f6446f72.PNG)

**Comment by galloscript** [comment]
Hi @AttilaART, just click in the top left corner of the graph viewport: 
![image](https://user-images.githubusercontent.com/3537058/71559181-787bef00-2a5b-11ea-8132-ce890b2157e6.png)
You can also delete this file to reset your gui configuration: [TexGraph_root]/Cache/imgui000400.ini

**Comment by AttilaART** [comment]
Thanks
