### ISSUE TITLE
Red Export output

### ISSUE THREAD

**Issue by AttilaART** [galloscript/TexGraph-Public#12]
when I export it comes out red+brightness
![aa](https://user-images.githubusercontent.com/59292387/71561938-9ce8c300-2a7d-11ea-8559-096da613ef11.png)
![a](https://user-images.githubusercontent.com/59292387/71561943-a540fe00-2a7d-11ea-8fce-8502ce09245d.png)
![TilesRoughness](https://user-images.githubusercontent.com/59292387/71561944-a8d48500-2a7d-11ea-9904-ea0d2539b131.png)

**Comment by galloscript** [comment]
Hi @AttilaART, grayscale textures only export data in red channel. Green and blue channels contain black. If you want data in all three channels use the "Color" node and plug the same or different grayscale textures on the three inputs.

**Comment by AttilaART** [comment]
Thank you
