### ISSUE TITLE
[Suggestion] MaterialX Support

### ISSUE THREAD

**Issue by jstone-lucasfilm** [galloscript/TexGraph-Public#2]
Hi David,

This looks like a great project, and I was curious if you'd considered using MaterialX for import and export of graphs.  Here's a simple example of a MaterialX file representing procedural marble for the Autodesk Standard Surface shader:

https://github.com/jstone-dev/MaterialX/blob/adsk_contrib/dev/resources/Materials/TestSuite/pbrlib/materials/standard_surface_marble_solid.mtlx

And here's the rendered result in the MaterialX viewer (see the upper-left teapot in the top image):

https://github.com/jstone-dev/MaterialX

Keep up the great work, and best of luck with this project!

-Jonathan

**Comment by galloscript** [comment]
Hello, there are no plans to export in other formats for now, but as it have an open format, any one can write a conversion at JSON / XML level. Thanks for the suggestion.
