### ISSUE TITLE
Crash after opening

### ISSUE THREAD

**Issue by Shohrukh1999** [galloscript/TexGraph-Public#3]
Hi David!
I have a problem. The program opens, shows a gray window and crashes in a few seconds. What is the reason? Maybe my computer is not powerful enough?

**Comment by galloscript** [comment]
Hello  @Shohrukh1999, can you tell me your PC specs? What Graphic card you have?

**Comment by Shohrukh1999** [comment]
My Graphic Card Nvidia Geforce 9500 GT.
Sorry for the late reply!

**Comment by galloscript** [comment]
Hello Shohrukh1999, your graphic card only supports OpenGL 2.1, and I'm using OpenGL 4.3 on TexGraph. Technically is possible to develop a TexGraph version using OpenGL 2.1 and computing the nodes on CPU or with fragment shaders, as in fact the prototype of this tool born this way, but there are no plans to develop it for now. 

Sorry.
