### ISSUE TITLE
preview window is just blue

### ISSUE THREAD

**Issue by Aevus-Eye** [galloscript/TexGraph-Public#4]
when i open the app, the preview window is just blue. it does not matter if i set an output node, the window stays blue. graphics card: nvidia geforce gtx 965M, supports open gl 4.6.0. 
![grafik](https://user-images.githubusercontent.com/42070251/58729791-9d878100-83ea-11e9-8afc-effa09a77f80.png)

**Comment by galloscript** [comment]
Hello @dontknow3d, is there any error in the Console Log Tab when you open the application? If you are not unsure, you can open TexGraph and just copy paste it's content here.

**Comment by Aevus-Eye** [comment]
i dont see any error there, but here it is:


Loading kernel ApplyBloomKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/ApplyBloom.comp.glsl
Loading kernel BlendKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Blend.comp.glsl
Loading kernel BloomFilterKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/BloomFilter.comp.glsl
Loading kernel BlurKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Blur.comp.glsl
Loading kernel CircleKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Circle.comp.glsl
Loading kernel ClampKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Clamp.comp.glsl
Loading kernel ColorKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Color.comp.glsl
Loading kernel ConvertToRGBA8Kernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Utils/ConvertToRGBA8.comp.glsl
Loading kernel CurvatureKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Curvature.comp.glsl
Loading kernel DrawCubemap
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/DrawCubemap.comp.glsl
Loading kernel DrawMesh
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/DrawMesh.vert.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/DrawMeshLib.frag.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/PBRViewer/DrawMesh.frag.glsl
Loading kernel EdgeDetectionKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/EdgeDetection.comp.glsl
Loading kernel GradientNoiseKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/GradientNoise.comp.glsl
Loading kernel GreyGradientMixKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/GreyGradientMix.comp.glsl
Loading kernel GreyKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Grey.comp.glsl
Loading kernel HashRemapKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoisesCommon.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/HashRemap.comp.glsl
Loading kernel HBAOKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoisesCommon.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/HBAO.comp.glsl
Loading kernel IQNoiseKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/IQNoise.comp.glsl
Loading kernel MaxKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Max.comp.glsl
Loading kernel MixKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Mix.comp.glsl
Loading kernel MultiplyKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Multiply.comp.glsl
Loading kernel NoiseTestKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoiseTest.comp.glsl
Loading kernel NormalKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Normal.comp.glsl
Loading kernel OffsetKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Offset.comp.glsl
Loading kernel OneMinusKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/OneMinus.comp.glsl
Loading kernel Perlin1Kernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoisesCommon.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Perlin1.comp.glsl
Loading kernel Polygon2DKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Polygon2D.comp.glsl
Loading kernel PowKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Pow.comp.glsl
Loading kernel RaymarchPreview
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/RaymarchPreview.comp.glsl
Loading kernel SquircleKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Squircle.comp.glsl
Loading kernel StepKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Step.comp.glsl
Loading kernel TilingKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoisesCommon.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Tiling.comp.glsl
Loading kernel VoronoiUltimateKernel
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/Common.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/NoisesCommon.glsl
Shader file loaded C:/Users/ae1admin1/AppData/Roaming/itch/apps/TexGraph/Public/Shaders/GLSL/Compute/VoronoiUltimate.comp.glsl

**Comment by galloscript** [comment]
No clues in the log @dontknow3d , try updating the drivers, if you know shader programming, try doing some test in the viewport shader.
