### ISSUE TITLE
[Improvement] Preview 3D

### ISSUE THREAD

**Issue by Shohrukh1999** [galloscript/TexGraph-Public#5]
Hi David! I expect, preview 3D window needs to be improved. For example, in AwesomeBump MMB (scrolling) for zooming, (pressing and dragging) the direction of the light; LMB to rotate; RMB to move.
P.S. Now I use the Nvidia GT 730 GDDR5 graphics card. OpenGL 4.6.

**Comment by galloscript** [comment]
Thanks for the suggestion, I take note of that. Maybe I implement a configurable input in the future to cover different user setups.
