### ISSUE TITLE
uInputFormat.y is always 1 if Input1 is set to "ANY"

### ISSUE THREAD

**Issue by SnowboundCabin** [galloscript/TexGraph-Public#9]
If Input1 is configured to take the format "ANY," uInputFormat.y is 1 no matter what the input format really is. Based on the way Multiply uses uInputFormat.y, it seems like it ought to be the number of channels - 1 for R, 4 for RGBA, just like uInputFormat.x. Because it remains 1 no matter what, the Multiply node will attempt to convert RGBA to RGBA, destroying the existing blue and green channels in the process and potentially wiping out the image entirely if there's no red in the red channel. Other nodes experience various issues as well; this isn't an issue with Multiply, and I first experienced it when trying to convert Max to work with ANY just like Multiply does. I've done a bunch of testing, and confirmed it is definitely this number not changing with format that causes the issue.

The input combinations (R, R) and (RGBA, R) work fine, and (R, RGBA) has its own problem that makes this one a moot point - See #8. Only the combination (RGBA, RGBA) has this issue.

Shown below is the issue as it affects Multiply. Red stays red, while blue and green disappear. Red appears to function because FF0000*FF0000=FF0000*FFFFFF.
![image](https://user-images.githubusercontent.com/21693905/60924815-227a7b80-a270-11e9-881c-cb9f0d66949c.png)

Here is the same exact nodes if the conversion code is commented out. (RGBA, RGBA) now works fine, at the cost of all other combinations working right.
![image](https://user-images.githubusercontent.com/21693905/60925033-8f8e1100-a270-11e9-91a0-ef17c850fbb7.png)

**Comment by galloscript** [comment]
Thanks for the report, I uploaded a new version 0.3.1 with the fix, also fixed Blend node that was affected by this bug and another bug in its shader. Now It should work as expected.

Previous:

![bug_channels](https://user-images.githubusercontent.com/3537058/60999133-add03b80-a35a-11e9-95ee-b69f9bac7e3e.png)

Now:

![bug_channels_fixed](https://user-images.githubusercontent.com/3537058/60999140-b4f74980-a35a-11e9-933f-6111f2095e0a.png)
